import type { Metadata } from "next";
import "./globals.css";
import { Oxanium } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { DataProvider } from "@/context/KeyContext";
import { ThemeProvider } from "@/components/ui/ThemeProvider";

const oxanium = Oxanium({
  variable: "--font-oxanium",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${oxanium.variable} bg-background antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <DataProvider>{children}</DataProvider>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
